FROM python:3.7 AS collector
WORKDIR /app
COPY . .
RUN pip3 install -r requirements.txt
ENV DJANGO_SETTINGS_MODULE=response.settings.collector
RUN python3 manage.py collectstatic --noinput --clear

FROM nginx:alpine
RUN rm /usr/share/nginx/html/index.html
COPY --from=collector /app/static /usr/share/nginx/html/static
