---
apiVersion: v1
kind: Service
metadata:
  name: response-unifier
  namespace: incident-response
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/component: web
  annotations:
    cloud.google.com/app-protocols: '{"http":"HTTP","https":"HTTPS"}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/component: web
